//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{


	 public partial class ManageProjekt
	 {

		  /// <summary>
		  /// LbProjekti control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.ListBox LbProjekti;

		  /// <summary>
		  /// txtNaziv control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox txtNaziv;

		  /// <summary>
		  /// ddlKlijent control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList ddlKlijent;

		  /// <summary>
		  /// txtDatum control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox txtDatum;

		  /// <summary>
		  /// ddlVoditeljProjekta control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList ddlVoditeljProjekta;

		  /// <summary>
		  /// BtnEdit control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnEdit;

		  /// <summary>
		  /// BtnAdd control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnAdd;

		  /// <summary>
		  /// BtnSave control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnSave;

		  /// <summary>
		  /// BtnDeaktiviraj control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnDeaktiviraj;

		  /// <summary>
		  /// lbZaposleniNaProjektu control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.ListBox lbZaposleniNaProjektu;
	 }
}
