//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{


	 public partial class ManageDjelatnik
	 {

		  /// <summary>
		  /// LbDjelatnici control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.ListBox LbDjelatnici;

		  /// <summary>
		  /// txtIme control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox txtIme;

		  /// <summary>
		  /// txtPrezime control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox txtPrezime;

		  /// <summary>
		  /// RegularExpressionValidator control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator;

		  /// <summary>
		  /// txtEmail control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox txtEmail;

		  /// <summary>
		  /// txtDatum control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox txtDatum;

		  /// <summary>
		  /// txtZaporka control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox txtZaporka;

		  /// <summary>
		  /// ddlTim control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList ddlTim;

		  /// <summary>
		  /// ddlTipDjelatnika control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList ddlTipDjelatnika;

		  /// <summary>
		  /// BtnEdit control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnEdit;

		  /// <summary>
		  /// BtnAdd control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnAdd;

		  /// <summary>
		  /// BtnAktiviraj control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnAktiviraj;

		  /// <summary>
		  /// BtnDeaktiviraj control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnDeaktiviraj;

		  /// <summary>
		  /// BtnSave control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnSave;

		  /// <summary>
		  /// lbProjekti control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.ListBox lbProjekti;
	 }
}
