//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{


	 public partial class TimReport
	 {

		  /// <summary>
		  /// lblTim control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Label lblTim;

		  /// <summary>
		  /// ddlTimovi control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList ddlTimovi;

		  /// <summary>
		  /// lblFrom control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Label lblFrom;

		  /// <summary>
		  /// DtpFrom control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox DtpFrom;

		  /// <summary>
		  /// lblTo control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Label lblTo;

		  /// <summary>
		  /// DtpTo control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox DtpTo;

		  /// <summary>
		  /// BtnSearch control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnSearch;

		  /// <summary>
		  /// gvTable control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.GridView gvTable;

		  /// <summary>
		  /// BtnCsv control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button BtnCsv;
	 }
}
