//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaSati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnosSati {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnosSati() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvidencijaSati.Resources.UnosSati", typeof(UnosSati).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilježe se sati za.
        /// </summary>
        public static string Bilježe_se_sati__za {
            get {
                return ResourceManager.GetString("Bilježe_se_sati_ za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Detalji {
            get {
                return ResourceManager.GetString("Detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Komentar {
            get {
                return ResourceManager.GetString("Komentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozdrav.
        /// </summary>
        public static string Pozdrav {
            get {
                return ResourceManager.GetString("Pozdrav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predaj.
        /// </summary>
        public static string Predaj {
            get {
                return ResourceManager.GetString("Predaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prekovremeni sati.
        /// </summary>
        public static string Prekovremeni_sati {
            get {
                return ResourceManager.GetString("Prekovremeni_sati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        public static string Projekt {
            get {
                return ResourceManager.GetString("Projekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjene spremljene!.
        /// </summary>
        public static string Promjene_spremljene {
            get {
                return ResourceManager.GetString("Promjene_spremljene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radni sati.
        /// </summary>
        public static string Radni_sati {
            get {
                return ResourceManager.GetString("Radni_sati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string Spremi {
            get {
                return ResourceManager.GetString("Spremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno.
        /// </summary>
        public static string Ukupno {
            get {
                return ResourceManager.GetString("Ukupno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string Uredi {
            get {
                return ResourceManager.GetString("Uredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabilježeno.
        /// </summary>
        public static string Zabiljezeno {
            get {
                return ResourceManager.GetString("Zabiljezeno", resourceCulture);
            }
        }
    }
}
