//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaSati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvidencijaSati.Resources.UserProfile", typeof(UserProfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zaposlenja.
        /// </summary>
        public static string Datum_zaposlenja {
            get {
                return ResourceManager.GetString("Datum_zaposlenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direktor.
        /// </summary>
        public static string Direktor {
            get {
                return ResourceManager.GetString("Direktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorarni djelatnik.
        /// </summary>
        public static string Honorarni_djelatnik {
            get {
                return ResourceManager.GetString("Honorarni_djelatnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova zaporka.
        /// </summary>
        public static string Nova_zaporka {
            get {
                return ResourceManager.GetString("Nova_zaporka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovi zaporku.
        /// </summary>
        public static string Ponovi_zaporku {
            get {
                return ResourceManager.GetString("Ponovi_zaporku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni zaporku.
        /// </summary>
        public static string Promijeni_zaporku {
            get {
                return ResourceManager.GetString("Promijeni_zaporku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stara zaporka.
        /// </summary>
        public static string Stara_zaporka {
            get {
                return ResourceManager.GetString("Stara_zaporka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip djelatnika.
        /// </summary>
        public static string Tip_djelatnika {
            get {
                return ResourceManager.GetString("Tip djelatnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voditelj tima.
        /// </summary>
        public static string Voditelj_tima {
            get {
                return ResourceManager.GetString("Voditelj_tima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposlenik.
        /// </summary>
        public static string Zaposlenik {
            get {
                return ResourceManager.GetString("Zaposlenik", resourceCulture);
            }
        }
    }
}
